### ISSUE TITLE
Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by projectwebseo** [infusionsoft/API-Sample-Code#11]
New to github, new to comments, new new new...

So it seems this is the old way and shouldn't be used in light of the new way.
None the less I could not get this to work.

xmlrpc.inc throws the "DEPRECATED Assigning the return value of new by reference is deprecated" on this =& 

I did some research and the resolution was to remove the & and it would run error free. I tried that and the script died at the call "$result = $client->send($call);"

If anyone can assist please do. Otherwise I'm finding a new tree to bark up...

**Comment by kressaty** [comment]
Hey @projectwebseo! Hopefully we can get you going. Your best bet to start working with the Infusionsoft API is to start with the new PHP SDK, which you can find here: https://github.com/infusionsoft/infusionsoft-php

There are several tutorials to get you going, which you can find on the developer portal here: https://developer.infusionsoft.com/tutorials/

I'd recommend starting with this one specifically: https://developer.infusionsoft.com/tutorials/getting-started-with-the-infusionsoft-php-sdk/

Since this repo is mostly deprecated and uses an outdated method of calling the API, you don't want to go down that path, as you'll eventually get stuck and have to move to the new methods anyways. 

There's also an active Facebook community that goes through API stuff all the time, check it out here: https://www.facebook.com/groups/infusionsoftapicommunity/?ref=bookmarks

Good luck!
